### ISSUE TITLE
Firefox compositor issues with pop ups/dialogue boxes

### ISSUE THREAD

**Issue by wallzero** [gamer-os/gamer-os#181] opened 2021-01-19 19:51 UTC
Firefox works great but has trouble rendering browser interface pop ups. For example, when installing Firefox extensions the user needs to click a pop up dialogue box, but it causes the screen to flicker and nothing appears.

**Comment by alkazar** [comment] 2021-01-21 02:06
This is essentially intended behaviour. The compositor ensures every window is run in full screen. In Xorg, even menus are windows, which is why this happens.

I can imagine a solution where we avoid doing the full screen on windows smaller than a certain size. However, I don't know how well that would work. Firefox and other desktop apps are not intended to be used in GamerOS, therefore this is unfortunately not a priority. Of course, PRs are welcome.

The work around is to use the "Toggle compositor" option from Steam Buddy which will dynamically switch between the SteamOS compositor and Openbox, a more traditional window manager.

Closing since this is a duplicate of https://github.com/gamer-os/steamos-compositor-plus/issues/30

**Closed by alkazar** 2021-01-21 02:06 UTC

**Comment by wallzero** [comment] 2021-01-21 22:33
Thanks. Toggling the compositor allowed me to install Firefox extensions.
