### ISSUE TITLE
Dual Shock 4 Controller Disconnects after Connecting 2nd Time

### ISSUE THREAD

**Issue by leocodeninja** [gamer-os/gamer-os#100] opened 2020-05-02 00:48 UTC
When first connecting a DS4 controller it works just fine. After the controller shuts off, when It  connects the controller just shuts off again.

To fix the issue I have to open the bluetooth settings, put the controller in pair mode and click connect in steams menu. This then causes steam to crash and exit. The controller works when I try and connect again.

It may have to do with the authorization settings in blumon or whatever is used to manage bluetooth.

**Comment by alkazar** [comment] 2020-05-02 01:01
Duplicate of #71 

There is a workaround there.

**Closed by alkazar** 2020-05-02 01:01 UTC

**Comment by leocodeninja** [comment] 2020-05-02 03:59
Thanks! Is this a problem with steam? I wish they would open source their client or actually fix bugs that have been present for 5+ years (Bugs in big picture mode like streams no showing, or adverts for sales not working, etc.)
