### ISSUE TITLE
N64 - Emulation no way to start

### ISSUE THREAD

**Issue by gamersalpha** [gamer-os/gamer-os#118] opened 2020-06-13 16:03 UTC
Hello there, so i put some N64 game like mario kart or mario 64, but when i lunch them i got nothing 

https://www.youtube.com/watch?v=nKWL09t0Wgc

do u have some info to found what is the probleme ?

thanks all

**Comment by alkazar** [comment] 2020-06-13 16:18
Duplicate of https://github.com/gamer-os/steam-buddy/issues/80

**Closed by alkazar** 2020-06-13 16:18 UTC
