### ISSUE TITLE
Bluetooth Controller Support

### ISSUE THREAD

**Issue by zediiiii** [gamer-os/gamer-os#141] opened 2020-09-20 01:23 UTC
SteamOS supports pairing bluetooth controlles-- any chance of adding the same feature to GamerOS?

**Comment by alkazar** [comment] 2020-09-20 02:52
Duplicate of https://github.com/gamer-os/gamer-os/issues/71

**Closed by alkazar** 2020-09-20 02:52 UTC

**Comment by zediiiii** [comment] 2020-09-20 15:14
@alkazar my fault -- bad bluetooth hardware after testing in another is.
