### ISSUE TITLE
No internet

### ISSUE THREAD

**Issue by testmandk2** [gamer-os/gamer-os#95] opened 2020-04-20 09:55 UTC
after boot up from USB and format of HDD no internet is detected
after i try to press ctrl-alt-f3 it tells me password is incorrect

**Comment by testmandk2** [comment] 2020-04-20 10:28
tried with 2 laptops and its the same error. tried with a 3. one and it works. i think its a ethernet driver problem. how can i make it work on the other 2? 

First laptop: ACER aspire m3 581tg (not working)
Second laptop: DELL inspiron 1545 (not working)
Third laptop: HP probook 6460b (working)

**Comment by alkazar** [comment] 2020-04-20 11:25
Did you connect all the computers with a wired connection?

**Comment by testmandk2** [comment] 2020-04-20 12:26
Yes i did

**Comment by alkazar** [comment] 2020-04-20 13:07
Then sorry, but I don't know. You might try searching for info on your network cards and compatibility with Linux and specifically Arch.

One thing that stands out is that there should be a warning first thing before the installer starts if the network failed to connect. Did you see this warning? If not, then either you are using an old installer or you just had some kind of intermittent network issue and could try again.

**Comment by testmandk2** [comment] 2020-04-20 13:12
Yes i did see that warning. 
I inserted the Acer harddrive into HP laptop and installed GamerOS. Then I removed the Acer harddrive and put it back inside Acer laptop and it seems to work with internet. 

Now I just have another problem. GamerOS is using integrated Intel graphics instead of dedicated Nvidia graphics

**Comment by rshamsnejad** [comment] 2020-05-21 09:59
@testmandk2 after getting the warning, have you tried continuing the installation ? At which point does it fail ?

**Comment by alkazar** [comment] 2020-06-05 02:34
It sounds like the original problem was solved. The problem with integrated graphics is a duplicate of #97

**Closed by alkazar** 2020-06-05 02:34 UTC
