### ISSUE TITLE
NVME Install Issues

### ISSUE THREAD

**Issue by wjrobe** [gamer-os/gamer-os#48] opened 2019-10-27 02:49 UTC
When trying to install on NVME drive, installer gives error on mkfs.vfat for bad blocks and quits.  Recommend fixing usage of mkfs.xfat because they drive was scanned and there are no bad blocks.

**Comment by alkazar** [comment] 2019-10-27 11:12
Duplicate of #47. I have instructions in that issue for a workaround. Let me know if it works for you.

**Closed by alkazar** 2019-10-27 11:12 UTC
