### ISSUE TITLE
Request : Compatibility : set system ideal resolution or resolution locking 

### ISSUE THREAD

**Issue by Thijzer** [gamer-os/gamer-os#208] opened 2021-03-10 20:22 UTC
This might be a bit of a weird request, but the ability to set your ideal resolution across the OS is something I'm lookign for.
I have a 4k device and often on older games or other menu systems like chat there is no menu scaling and everything looks small.

It might be handy to set your own preferred resolution somewhere in for example steam buddy the fix this issue.

I know you have per game options but that's not the point, other menu's that don't have vector scaling still won't work.
I prefer a global setting for this.

**Comment by alkazar** [comment] 2021-03-14 03:58
Closing as duplicate of https://github.com/gamer-os/steam-buddy/issues/126

See that issue for a workaround.

**Closed by alkazar** 2021-03-14 03:58 UTC
