### ISSUE TITLE
Can't install on GTX 1660 Super

### ISSUE THREAD

**Issue by Mohandevir** [gamer-os/gamer-os#86] opened 2020-03-28 13:34 UTC
Hello!

I've been able to install GamerOS on my old i7-3770 with GTX 960 easily following the standard installer, but I tried doing the same with my new Ryzen 5 3600 and GTX 1660 Super (nvme drive) and all I get is an unreadable blurry screen and at some point it gets stuck on a half blue screen.

It stops being usable after the initial installer menu (Install GamerOS, uefi bootloader, Reboot to system settings...).

Any help would be awesome.

Thanks again.

**Comment by Mohandevir** [comment] 2020-03-28 16:07
The problem is not resolved, but I found a workaround: 
Installing GamerOs with the GTX 960 in my Ryzen 5 3600 rig.

Nouveau problem? Could it be possible to include the Nvidia driver at install?

Thanks anyway. I really do like GamerOS.

**Comment by alkazar** [comment] 2020-03-28 18:00
Hi, can you try the new ISO installer here: https://github.com/gamer-os/install-media/releases/download/2020-03-12/gameros-2020.03.12-x86_64.iso

This sounds like a duplicate of https://github.com/gamer-os/install-media/issues/8

**Closed** 2020-04-12 19:21 UTC
